### ISSUE TITLE
ValueError: non-broadcastable output operand with shape (200,) doesn't match the broadcast shape (200,200)

### ISSUE THREAD

**Issue by ranigb** [MaxHalford/starboost#1]
When trying to use starboost I am running into a problem in boosting.py line 124. There is mismatch between the shapes of y_pred[:,i] and direction. I think the line should be:
### y_pred[:, i] += self.learning_rate * direction[:, i]

**Comment by MaxHalford** [comment]
Hello! I encourage you to open a pull request, ideally with a unit test :)
