### ISSUE TITLE
base_estimator

### ISSUE THREAD

**Issue by yupinglin0301** [MaxHalford/starboost#2]
Hi, is that I can change the base_estimator to another model, e.g. Linear regression ?

**Comment by MaxHalford** [comment]
Yes, you can pass any base estimator, in theory. Have you tried?

**Comment by yupinglin0301** [comment]
Sorry, I have not yet given a try, just ask it before try. Thank you for your response.

**Comment by MaxHalford** [comment]
No problem! Be aware I'm not maintaining this project anymore, so I won't be able to fix things. Too many other priorities :)
